// Generated by Supabase (generate_typescript_types). Regenerate after every migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      bank_connections: {
        Row: {
          account_iban_tail: string | null
          account_name: string | null
          account_uid: string | null
          accounts: Json
          aspsp_country: string
          aspsp_name: string
          auth_state: string | null
          created_at: string
          currency: string | null
          id: number
          last_balance: number | null
          last_balance_at: string | null
          last_error: string | null
          required_psu_headers: string[]
          session_id: string | null
          status: string
          updated_at: string
          user_id: string
          valid_until: string | null
        }
        Insert: {
          account_iban_tail?: string | null
          account_name?: string | null
          account_uid?: string | null
          accounts?: Json
          aspsp_country: string
          aspsp_name: string
          auth_state?: string | null
          created_at?: string
          currency?: string | null
          id?: never
          last_balance?: number | null
          last_balance_at?: string | null
          last_error?: string | null
          required_psu_headers?: string[]
          session_id?: string | null
          status?: string
          updated_at?: string
          user_id: string
          valid_until?: string | null
        }
        Update: {
          account_iban_tail?: string | null
          account_name?: string | null
          account_uid?: string | null
          accounts?: Json
          aspsp_country?: string
          aspsp_name?: string
          auth_state?: string | null
          created_at?: string
          currency?: string | null
          id?: never
          last_balance?: number | null
          last_balance_at?: string | null
          last_error?: string | null
          required_psu_headers?: string[]
          session_id?: string | null
          status?: string
          updated_at?: string
          user_id?: string
          valid_until?: string | null
        }
        Relationships: []
      }
      bank_credentials: {
        Row: {
          app_id: string | null
          key_secret_id: string | null
          provider: string
          updated_at: string
          user_id: string
        }
        Insert: {
          app_id?: string | null
          key_secret_id?: string | null
          provider?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          app_id?: string | null
          key_secret_id?: string | null
          provider?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      budget_records: {
        Row: {
          amount: number
          completed: boolean
          created_at: string
          date_from: string
          date_to: string
          deleted_at: string | null
          id: number
          legacy_id: number | null
          series_id: number | null
          series_index: number | null
          title: string
          type: Database["public"]["Enums"]["record_type"]
          updated_at: string
          user_id: string
        }
        Insert: {
          amount: number
          completed?: boolean
          created_at?: string
          date_from: string
          date_to: string
          deleted_at?: string | null
          id?: never
          legacy_id?: number | null
          series_id?: number | null
          series_index?: number | null
          title: string
          type: Database["public"]["Enums"]["record_type"]
          updated_at?: string
          user_id?: string
        }
        Update: {
          amount?: number
          completed?: boolean
          created_at?: string
          date_from?: string
          date_to?: string
          deleted_at?: string | null
          id?: never
          legacy_id?: number | null
          series_id?: number | null
          series_index?: number | null
          title?: string
          type?: Database["public"]["Enums"]["record_type"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "budget_records_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "budget_series"
            referencedColumns: ["id"]
          },
        ]
      }
      budget_series: {
        Row: {
          amount: number
          created_at: string
          ends_on: string | null
          first_date: string
          id: number
          period_days: number
          title: string
          type: Database["public"]["Enums"]["record_type"]
          updated_at: string
          user_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          ends_on?: string | null
          first_date: string
          id?: never
          period_days?: number
          title: string
          type: Database["public"]["Enums"]["record_type"]
          updated_at?: string
          user_id?: string
        }
        Update: {
          amount?: number
          created_at?: string
          ends_on?: string | null
          first_date?: string
          id?: never
          period_days?: number
          title?: string
          type?: Database["public"]["Enums"]["record_type"]
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      settings: {
        Row: {
          balance: number
          balance_source: string
          balance_updated_at: string
          critical_balance: number
          currency: string
          daily_expenses: number
          locale: string
          scale_months: number
          updated_at: string
          user_id: string
          warning_balance: number
        }
        Insert: {
          balance?: number
          balance_source?: string
          balance_updated_at?: string
          critical_balance?: number
          currency?: string
          daily_expenses?: number
          locale?: string
          scale_months?: number
          updated_at?: string
          user_id: string
          warning_balance?: number
        }
        Update: {
          balance?: number
          balance_source?: string
          balance_updated_at?: string
          critical_balance?: number
          currency?: string
          daily_expenses?: number
          locale?: string
          scale_months?: number
          updated_at?: string
          user_id?: string
          warning_balance?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      bank_clear_credentials: { Args: { p_user: string }; Returns: undefined }
      bank_cron_secret: { Args: never; Returns: string }
      bank_get_credentials: {
        Args: { p_user: string }
        Returns: {
          app_id: string
          private_key: string
        }[]
      }
      bank_set_credentials: {
        Args: { p_app_id: string; p_private_key: string; p_user: string }
        Returns: undefined
      }
      repeat_monthly: { Args: { p_record_id: number }; Returns: number }
      stop_series_from: { Args: { p_record_id: number }; Returns: undefined }
      update_series_from: {
        Args: {
          p_amount: number
          p_date_from: string
          p_date_to: string
          p_record_id: number
          p_title: string
          p_type: Database["public"]["Enums"]["record_type"]
        }
        Returns: undefined
      }
    }
    Enums: {
      record_type: "income" | "expense"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export const Constants = {
  public: {
    Enums: {
      record_type: ["income", "expense"],
    },
  },
} as const
